local highlight = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()
    local c = require("dast.colors").get_colors()

    highlight(0, "Normal",         { fg = c.Front, bg = c.Back })
    highlight(0, "ColorColumn",    { fg = c.None, bg = c.CursorDarkDark })
    highlight(0, "Cursor",         { fg = c.CursorDark, bg = c.CursorLight })
    highlight(0, "CursorLine",     { bg = c.CursorDarkDark })
    highlight(0, "CursorColumn",   { fg = c.None, bg = c.CursorDarkDark })
    highlight(0, "Directory",      { fg = c.Blue, bg = c.Back })
    highlight(0, "DiffAdd",        { fg = c.Green, bg = c.None })
    highlight(0, "DiffChange",     { fg = c.None, bg = c.DiffRedDark })
    highlight(0, "DiffDelete",     { fg = c.Red, bg = c.None })
    highlight(0, "DiffText",       { fg = c.None, bg = c.DiffRedLight })
    highlight(0, "EndOfBuffer",    { fg = c.Back, bg = c.None })
    highlight(0, "ErrorMsg",       { fg = c.Red, bg = c.Back })
    highlight(0, "VertSplit",      { fg = c.SplitDark, bg = c.Back })
    highlight(0, "WinSeparator",   { link = "VertSplit" })
    highlight(0, "Folded",         { fg = c.None, bg = c.FoldBackground })
    highlight(0, "FoldColumn",     { fg = c.LineNumber, bg = c.Back })
    highlight(0, "SignColumn",     { fg = c.None, bg = c.Back })
    highlight(0, "IncSearch",      { fg = c.None, bg = c.Selection })
    highlight(0, "LineNr",         { fg = c.LineNumber, bg = c.Back })
    highlight(0, "CursorLineNr",   { fg = c.Front, bg = c.Back })
    highlight(0, "MatchParen",     { fg = c.None, bg = c.CursorDark })
    highlight(0, "ModeMsg",        { fg = c.Front, bg = c.LeftDark })
    highlight(0, "MoreMsg",        { fg = c.Front, bg = c.LeftDark })
    highlight(0, "NonText",        { fg = c.LineNumber or c.TabOther, bg = c.None })
    highlight(0, "Pmenu",          { fg = c.PopupFront, bg = c.PopupBack })
    highlight(0, "PmenuSel",       { fg = c.PopupFront or c.Back, bg = c.PopupHighlightBlue })
    highlight(0, "PmenuSbar",      { fg = c.None, bg = c.PopupHighlightGray })
    highlight(0, "PmenuThumb",     { fg = c.None, bg = c.PopupFront })
    highlight(0, "Question",       { fg = c.Blue, bg = c.Back })
    highlight(0, "Search",         { fg = c.None, bg = c.Selection })
    highlight(0, "SpecialKey",     { fg = c.Blue, bg = c.None })
    highlight(0, "StatusLine",     { fg = c.Front, bg = c.LeftMid })
    highlight(0, "StatusLineNC",   { fg = c.Front, bg = c.LeftDark })
    highlight(0, "TabLine",        { fg = c.Front, bg = c.TabOther })
    highlight(0, "TabLineFill",    { fg = c.Front, bg = c.TabOutside })
    highlight(0, "TabLineSel",     { fg = c.Front, bg = c.TabCurrent })
    highlight(0, "Title",          { fg = c.None, bg = c.None, bold = true })
    highlight(0, "Visual",         { fg = c.None, bg = c.Selection })
    highlight(0, "VisualNOS",      { fg = c.None, bg = c.Selection })
    highlight(0, "WarningMsg",     { fg = c.Red, bg = c.Back, bold = true })
    highlight(0, "WildMenu",       { fg = c.None, bg = c.Selection })
    highlight(0, "Comment",        { fg = c.Gray, bg = c.None, italic = false })
    highlight(0, "Constant",       { fg = c.Blue, bg = c.None })
    highlight(0, "String",         { fg = c.Green, bg = c.None })
    highlight(0, "Character",      { fg = c.Green, bg = c.None })
    highlight(0, "Number",         { fg = c.Pink, bg = c.None })
    highlight(0, "Boolean",        { fg = c.Blue, bg = c.None })
    highlight(0, "Float",          { fg = c.Pink, bg = c.None })
    highlight(0, "Identifier",     { fg = c.Front, bg = c.None })
    highlight(0, "Function",       { fg = c.Yellow, bg = c.None })
    highlight(0, "Statement",      { fg = c.Blue, bg = c.None })
    highlight(0, "Conditional",    { fg = c.Blue, bg = c.None })
    highlight(0, "Repeat",         { fg = c.Blue, bg = c.None })
    highlight(0, "Label",          { fg = c.Blue, bg = c.None })
    highlight(0, "Operator",       { fg = c.Blue, bg = c.None })
    highlight(0, "Keyword",        { fg = c.Blue, bg = c.None })
    highlight(0, "Exception",      { fg = c.Blue, bg = c.None })
    highlight(0, "PreProc",        { fg = c.Blue, bg = c.None })
    highlight(0, "Include",        { fg = c.Blue, bg = c.None })
    highlight(0, "Define",         { fg = c.Blue, bg = c.None })
    highlight(0, "Macro",          { fg = c.Blue, bg = c.None })
    highlight(0, "Type",           { fg = c.BlueGreen, bg = c.None })
    highlight(0, "StorageClass",   { fg = c.Blue, bg = c.None })
    highlight(0, "Structure",      { fg = c.BlueGreen, bg = c.None })
    highlight(0, "Typedef",        { fg = c.BlueGreen, bg = c.None })
    highlight(0, "Special",        { fg = c.Yellow, bg = c.None })
    highlight(0, "SpecialChar",    { fg = c.Front, bg = c.None })
    highlight(0, "Tag",            { fg = c.Front, bg = c.None })
    highlight(0, "Delimiter",      { fg = c.Front, bg = c.None })
    highlight(0, "SpecialComment", { fg = c.Gray, bg = c.None })
    highlight(0, "Debug",          { fg = c.Front, bg = c.None })
    highlight(0, "Underlined",     { fg = c.None, bg = c.None, underline = true })
    highlight(0, "Conceal",        { fg = c.Front, bg = c.Back })
    highlight(0, "Ignore",         { fg = c.Front, bg = c.None })
    highlight(0, "Error",          { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    highlight(0, "Todo",           { fg = c.Yellow, bg = c.Back, bold = true })
    highlight(0, "SpellBad",       { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    highlight(0, "SpellCap",       { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    highlight(0, "SpellRare",      { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    highlight(0, "SpellLocal",     { fg = c.Red, bg = c.Back, undercurl = true, sp = c.Red })
    highlight(0, "Whitespace",     { fg = c.LineNumber or c.TabOther })

    -- Treesitter
    highlight(0, "@error",                         { fg = c.Red, bg = c.None })
    highlight(0, "@punctuation.bracket",           { fg = c.Front, bg = c.None })
    highlight(0, "@punctuation.special",           { fg = c.Front, bg = c.None })
    highlight(0, "@comment",                       { fg = c.Gray, bg = c.None, italic = false })
    highlight(0, "@constant",                      { fg = c.Blue, bg = c.None })
    highlight(0, "@constant.builtin",              { fg = c.Blue, bg = c.None })
    highlight(0, "@constant.macro",                { fg = c.Blue, bg = c.None })
    highlight(0, "@string.regex",                  { fg = c.Orange, bg = c.None })
    highlight(0, "@string",                        { fg = c.Green, bg = c.None })
    highlight(0, "@character",                     { fg = c.Orange, bg = c.None })
    highlight(0, "@number",                        { fg = c.Pink, bg = c.None })
    highlight(0, "@boolean",                       { fg = c.Blue, bg = c.None })
    highlight(0, "@float",                         { fg = c.Orange, bg = c.None })
    highlight(0, "@annotation",                    { fg = c.Orange, bg = c.None })
    highlight(0, "decorated_definition.decorator", { fg = c.Orange, bg = c.None })
    highlight(0, "@attribute",                     { fg = c.BlueGreen, bg = c.None })
    highlight(0, "@attribute.builtin",             { fg = c.BlueGreen, bg = c.None })
    highlight(0, "@namespace",                     { fg = c.BlueGreen, bg = c.None })
    highlight(0, "@function.builtin",              { fg = c.Yellow, bg = c.None })
    highlight(0, "@function",                      { fg = c.Yellow, bg = c.None })
    highlight(0, "@function.macro",                { fg = c.Yellow, bg = c.None })
    highlight(0, "@parameter",                     { fg = c.Front, bg = c.None })
    highlight(0, "@parameter.reference",           { fg = c.Front, bg = c.None })
    highlight(0, "@method",                        { fg = c.Yellow, bg = c.None })
    highlight(0, "@field",                         { fg = c.Front, bg = c.None })
    highlight(0, "@property",                      { fg = c.Front, bg = c.None })
    highlight(0, "@constructor",                   { fg = c.Yellow, bg = c.None })
    highlight(0, "@conditional",                   { fg = c.Blue, bg = c.None })
    highlight(0, "@repeat",                        { fg = c.Blue, bg = c.None })
    highlight(0, "@label",                         { fg = c.Front, bg = c.None })
    highlight(0, "@keyword",                       { fg = c.Blue, bg = c.None })
    highlight(0, "@keyword.function",              { fg = c.Blue, bg = c.None })
    highlight(0, "@keyword.operator",              { fg = c.Blue, bg = c.None })
    highlight(0, "@operator",                      { fg = c.Blue, bg = c.None })
    highlight(0, "@exception",                     { fg = c.Blue, bg = c.None })
    highlight(0, "@type",                          { fg = c.BlueGreen, bg = c.None })
    highlight(0, "@type.builtin",                  { fg = c.BlueGreen, bg = c.None })
    highlight(0, "@type.qualifier",                { fg = c.Blue, bg = c.None })
    highlight(0, "@storageClass",                  { fg = c.BlueGreen, bg = c.None })
    highlight(0, "@structure",                     { fg = c.BlueGreen, bg = c.None })
    highlight(0, "@include",                       { fg = c.Blue, bg = c.None })
    highlight(0, "@variable",                      { fg = c.Front, bg = c.None })
    highlight(0, "@variable.builtin",              { fg = c.Blue, bg = c.None })
    highlight(0, "@text",                          { fg = c.Front, bg = c.None })
    highlight(0, "@text.underline",                { fg = c.Yellow, bg = c.None })
    highlight(0, "@tag",                           { fg = c.Blue, bg = c.None })
    highlight(0, "@tag.delimiter",                 { fg = c.Gray, bg = c.None })
    highlight(0, "@tag.attribute",                 { fg = c.Front, bg = c.None })

    highlight(0, "@text.title",                   { fg = c.Blue or c.Yellow, bold = true })
    highlight(0, "@text.literal",                 { fg = c.Front, bg = c.None })
    highlight(0, "@text.literal.markdown",        { fg = c.Orange, bg = c.None })
    highlight(0, "@text.literal.markdown_inline", { fg = c.Orange, bg = c.None })
    highlight(0, "@text.emphasis",                { fg = c.Front, bg = c.None, italic = true })
    highlight(0, "@text.strike",                  { fg = c.Front, bg = c.None, strikethrough = true })
    highlight(0, "@text.strong",                  { fg = c.Blue or c.Violet, bold = true })
    highlight(0, "@text.uri",                     { fg = c.Front, bg = c.None })
    highlight(0, "@textReference",                { fg = c.Orange or c.Yellow })
    highlight(0, "@punctuation.delimiter",        { fg = c.Front, bg = c.None })
    highlight(0, "@stringEscape",                 { fg = c.Orange or c.Yellow, bold = true })

    highlight(0, "@text.note",    { fg = c.BlueGreen, bg = c.None, bold = true })
    highlight(0, "@text.warning", { fg = c.Yellow, bg = c.None, bold = true })
    highlight(0, "@text.danger",  { fg = c.Red, bg = c.None, bold = true })

    highlight(0, "@text.diff.add",    { link = "DiffAdd" })
    highlight(0, "@text.diff.delete", { link = "DiffDelete" })

    -- LSP semantic tokens
    highlight(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
    highlight(0, "@lsp.type.type",                   { link = "@type" })
    highlight(0, "@lsp.type.typeParameter",          { link = "@type" })
    highlight(0, "@lsp.type.macro",                  { link = "@constant" })
    highlight(0, "@lsp.type.enumMember",             { link = "@constant" })
    highlight(0, "@event",                           { link = "Identifier" })
    highlight(0, "@interface",                       { link = "Identifier" })
    highlight(0, "@modifier",                        { link = "Identifier" })
    highlight(0, "@regexp",                          { fg = c.Red, bg = c.None })
    highlight(0, "@decorator",                       { link = "Identifier" })

    -- Markdown
    highlight(0, "markdownBold",               { fg = c.Blue or c.Yellow, bold = true })
    highlight(0, "markdownCode",               { fg = c.Orange, bg = c.None })
    highlight(0, "markdownRule",               { fg = c.Blue or c.Yellow, bold = true })
    highlight(0, "markdownCodeDelimiter",      { fg = c.Front, bg = c.None })
    highlight(0, "markdownHeadingDelimiter",   { fg = c.Blue or c.Yellow, bg = c.None })
    highlight(0, "markdownFootnote",           { fg = c.Orange or c.Yellow, bg = c.None })
    highlight(0, "markdownFootnoteDefinition", { fg = c.Orange or c.Yellow })
    highlight(0, "markdownUrl",                { fg = c.Front, bg = c.None, underline = true })
    highlight(0, "markdownLinkText",           { fg = c.Orange or c.Yellow })
    highlight(0, "markdownEscape",             { fg = c.Orange or c.Yellow })

    -- Asciidoc
    highlight(0, "asciidocAttributeEntry",                { fg = c.Yellow })
    highlight(0, "asciidocAttributeList",                 { fg = c.Pink })
    highlight(0, "asciidocAttributeRef",                  { fg = c.Yellow })
    highlight(0, "asciidocHLabel",                        { fg = c.Blue, bold = true })
    highlight(0, "asciidocListingBlock",                  { fg = c.Orange })
    highlight(0, "asciidocMacroAttributes",               { fg = c.Yellow })
    highlight(0, "asciidocOneLineTitle",                  { fg = c.Blue, bold = true })
    highlight(0, "asciidocPassthroughBlock",              { fg = c.Blue })
    highlight(0, "asciidocQuotedMonospaced",              { fg = c.Orange })
    highlight(0, "asciidocTriplePlusPassthrough",         { fg = c.Yellow })
    highlight(0, "asciidocMacro",                         { fg = c.Pink })
    highlight(0, "asciidocAdmonition",                    { fg = c.Orange })
    highlight(0, "asciidocQuotedEmphasized",              { fg = c.Blue, italic = true })
    highlight(0, "asciidocQuotedEmphasized2",             { fg = c.Blue, italic = true })
    highlight(0, "asciidocQuotedEmphasizedItalic",        { fg = c.Blue, italic = true })
    highlight(0, "asciidocBackslash",                     { link = "Keyword" })
    highlight(0, "asciidocQuotedBold",                    { link = "markdownBold" })
    highlight(0, "asciidocQuotedMonospaced2",             { link = "asciidocQuotedMonospaced" })
    highlight(0, "asciidocQuotedUnconstrainedBold",       { link = "asciidocQuotedBold" })
    highlight(0, "asciidocQuotedUnconstrainedEmphasized", { link = "asciidocQuotedEmphasized" })
    highlight(0, "asciidocURL",                           { link = "markdownUrl" })

    -- JSON
    highlight(0, "jsonKeyword", { fg = c.Front, bg = c.None })
    highlight(0, "jsonEscape",  { fg = c.Yellow, bg = c.None })
    highlight(0, "jsonNull",    { fg = c.Blue, bg = c.None })
    highlight(0, "jsonBoolean", { fg = c.Blue, bg = c.None })

    -- HTML
    highlight(0, "htmlTag",            { fg = c.Gray, bg = c.None })
    highlight(0, "htmlEndTag",         { fg = c.Gray, bg = c.None })
    highlight(0, "htmlTagName",        { fg = c.Blue, bg = c.None })
    highlight(0, "htmlSpecialTagName", { fg = c.Blue, bg = c.None })
    highlight(0, "htmlArg",            { fg = c.LightBlue, bg = c.None })

    -- PHP
    highlight(0, "phpStaticClasses", { fg = c.BlueGreen, bg = c.None })
    highlight(0, "phpMethod",        { fg = c.Yellow, bg = c.None })
    highlight(0, "phpClass",         { fg = c.BlueGreen, bg = c.None })
    highlight(0, "phpFunction",      { fg = c.Yellow, bg = c.None })
    highlight(0, "phpInclude",       { fg = c.Blue, bg = c.None })
    highlight(0, "phpUseClass",      { fg = c.BlueGreen, bg = c.None })
    highlight(0, "phpRegion",        { fg = c.BlueGreen, bg = c.None })
    highlight(0, "phpMethodsVar",    { fg = c.Front, bg = c.None })

    -- CSS
    highlight(0, "cssBraces",          { fg = c.Front, bg = c.None })
    highlight(0, "cssInclude",         { fg = c.Pink, bg = c.None })
    highlight(0, "cssTagName",         { fg = c.Yellow, bg = c.None })
    highlight(0, "cssClassName",       { fg = c.Yellow, bg = c.None })
    highlight(0, "cssPseudoClass",     { fg = c.Yellow, bg = c.None })
    highlight(0, "cssPseudoClassId",   { fg = c.Yellow, bg = c.None })
    highlight(0, "cssPseudoClassLang", { fg = c.Yellow, bg = c.None })
    highlight(0, "cssIdentifier",      { fg = c.Yellow, bg = c.None })
    highlight(0, "cssProp",            { fg = c.LightBlue, bg = c.None })
    highlight(0, "cssDefinition",      { fg = c.LightBlue, bg = c.None })
    highlight(0, "cssAttr",            { fg = c.Orange, bg = c.None })
    highlight(0, "cssAttrRegion",      { fg = c.Orange, bg = c.None })
    highlight(0, "cssColor",           { fg = c.Orange, bg = c.None })
    highlight(0, "cssFunction",        { fg = c.Yellow, bg = c.None })
    highlight(0, "cssFunctionName",    { fg = c.Orange, bg = c.None })
    highlight(0, "cssVendor",          { fg = c.Orange, bg = c.None })
    highlight(0, "cssValueNumber",     { fg = c.Green, bg = c.None })
    highlight(0, "cssValueLength",     { fg = c.Orange, bg = c.None })
    highlight(0, "cssUnitDecorators",  { fg = c.Orange, bg = c.None })
    highlight(0, "cssStyle",           { fg = c.LightBlue, bg = c.None })
    highlight(0, "cssImportant",       { fg = c.Blue, bg = c.None })

    -- JavaScript
    highlight(0, "jsVariableDef",        { fg = c.Front, bg = c.None })
    highlight(0, "jsFuncArgs",           { fg = c.Front, bg = c.None })
    highlight(0, "jsFuncBlock",          { fg = c.Front, bg = c.None })
    highlight(0, "jsRegexpString",       { fg = c.LightRed, bg = c.None })
    highlight(0, "jsThis",               { fg = c.Blue, bg = c.None })
    highlight(0, "jsOperatorKeyword",    { fg = c.Blue, bg = c.None })
    highlight(0, "jsDestructuringBlock", { fg = c.Front, bg = c.None })
    highlight(0, "jsObjectKey",          { fg = c.Fron, bg = c.None })
    highlight(0, "jsGlobalObjects",      { fg = c.BlueGreen, bg = c.None })
    highlight(0, "jsModuleKeyword",      { fg = c.Front, bg = c.None })
    highlight(0, "jsClassDefinition",    { fg = c.BlueGreen, bg = c.None })
    highlight(0, "jsClassKeyword",       { fg = c.Blue, bg = c.None })
    highlight(0, "jsExtendsKeyword",     { fg = c.Blue, bg = c.None })
    highlight(0, "jsExportDefault",      { fg = c.Blue, bg = c.None })
    highlight(0, "jsFuncCall",           { fg = c.Yellow, bg = c.None })
    highlight(0, "jsObjectValue",        { fg = c.Front, bg = c.None })
    highlight(0, "jsParen",              { fg = c.Front, bg = c.None })
    highlight(0, "jsObjectProp",         { fg = c.Front, bg = c.None })
    highlight(0, "jsIfElseBlock",        { fg = c.Front, bg = c.None })
    highlight(0, "jsParenIfElse",        { fg = c.Front, bg = c.None })
    highlight(0, "jsSpreadOperator",     { fg = c.Blue, bg = c.None })
    highlight(0, "jsSpreadExpression",   { fg = c.Front, bg = c.None })

    -- Typescript
    highlight(0, "typescriptLabel",                 { fg = c.Front, bg = c.None })
    highlight(0, "typescriptExceptions",            { fg = c.Front, bg = c.None })
    highlight(0, "typescriptBraces",                { fg = c.Front, bg = c.None })
    highlight(0, "typescriptEndColons",             { fg = c.Front, bg = c.None })
    highlight(0, "typescriptParens",                { fg = c.Front, bg = c.None })
    highlight(0, "typescriptDocTags",               { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptDocComment",            { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptLogicSymbols",          { fg = c.Front, bg = c.None })
    highlight(0, "typescriptImport",                { fg = c.Pink, bg = c.None })
    highlight(0, "typescriptBOM",                   { fg = c.Front, bg = c.None })
    highlight(0, "typescriptVariableDeclaration",   { fg = c.Front, bg = c.None })
    highlight(0, "typescriptVariable",              { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptExport",                { fg = c.Pink, bg = c.None })
    highlight(0, "typescriptAliasDeclaration",      { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptAliasKeyword",          { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptClassName",             { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptAccessibilityModifier", { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptOperator",              { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptArrowFunc",             { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptMethodAccessor",        { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptMember",                { fg = c.Orange, bg = c.None })
    highlight(0, "typescriptTypeReference",         { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptTemplateSB",            { fg = c.Yellow, bg = c.None })
    highlight(0, "typescriptArrowFuncArg",          { fg = c.Front, bg = c.None })
    highlight(0, "typescriptParamImpl",             { fg = c.Front, bg = c.None })
    highlight(0, "typescriptFuncComma",             { fg = c.Front, bg = c.None })
    highlight(0, "typescriptCastKeyword",           { fg = c.Front, bg = c.None })
    highlight(0, "typescriptCall",                  { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptCase",                  { fg = c.Front, bg = c.None })
    highlight(0, "typescriptReserved",              { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptDefault",               { fg = c.Front, bg = c.None })
    highlight(0, "typescriptDecorator",             { fg = c.Orange, bg = c.None })
    highlight(0, "typescriptPredefinedType",        { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptClassHeritage",         { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptClassExtends",          { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptClassKeyword",          { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptBlock",                 { fg = c.Front, bg = c.None })
    highlight(0, "typescriptDOMDocProp",            { fg = c.Front, bg = c.None })
    highlight(0, "typescriptTemplateSubstitution",  { fg = c.Front, bg = c.None })
    highlight(0, "typescriptClassBlock",            { fg = c.Front, bg = c.None })
    highlight(0, "typescriptFuncCallArg",           { fg = c.Front, bg = c.None })
    highlight(0, "typescriptIndexExpr",             { fg = c.Front, bg = c.None })
    highlight(0, "typescriptConditionalParen",      { fg = c.Front, bg = c.None })
    highlight(0, "typescriptArray",                 { fg = c.Orange, bg = c.None })
    highlight(0, "typescriptES6SetProp",            { fg = c.Front, bg = c.None })
    highlight(0, "typescriptObjectLiteral",         { fg = c.Front, bg = c.None })
    highlight(0, "typescriptTypeParameter",         { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptEnumKeyword",           { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptEnum",                  { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptLoopParen",             { fg = c.Front, bg = c.None })
    highlight(0, "typescriptParenExp",              { fg = c.Front, bg = c.None })
    highlight(0, "typescriptModule",                { fg = c.Front, bg = c.None })
    highlight(0, "typescriptAmbientDeclaration",    { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptFuncTypeArrow",         { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptInterfaceHeritage",     { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptInterfaceName",         { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptInterfaceKeyword",      { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptInterfaceExtends",      { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptGlobal",                { fg = c.BlueGreen, bg = c.None })
    highlight(0, "typescriptAsyncFuncKeyword",      { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptFuncKeyword",           { fg = c.Blue, bg = c.None })
    highlight(0, "typescriptGlobalMethod",          { fg = c.Yellow, bg = c.None })
    highlight(0, "typescriptPromiseMethod",         { fg = c.Yellow, bg = c.None })

    -- XML
    highlight(0, "xmlTag",      { fg = c.Blue, bg = c.None })
    highlight(0, "xmlTagName",  { fg = c.Blue, bg = c.None })
    highlight(0, "xmlEndTag",   { fg = c.Blue, bg = c.None })

    -- Ruby
    highlight(0, "rubyClassNameTag", { fg = c.BlueGreen, bg = c.None })
    highlight(0, "rubyClassName",    { fg = c.BlueGreen, bg = c.None })
    highlight(0, "rubyModuleName",   { fg = c.BlueGreen, bg = c.None })
    highlight(0, "rubyConstant",     { fg = c.BlueGreen, bg = c.None })

    -- Golang
    highlight(0, "goPackage",               { fg = c.Blue, bg = c.None })
    highlight(0, "goImport",                { fg = c.Blue, bg = c.None })
    highlight(0, "goVar",                   { fg = c.Blue, bg = c.None })
    highlight(0, "goConst",                 { fg = c.Blue, bg = c.None })
    highlight(0, "goStatement",             { fg = c.Pink, bg = c.None })
    highlight(0, "goType",                  { fg = c.BlueGreen, bg = c.None })
    highlight(0, "goSignedInts",            { fg = c.Pink, bg = c.None })
    highlight(0, "goUnsignedInts",          { fg = c.Pink, bg = c.None })
    highlight(0, "goFloats",                { fg = c.Pink, bg = c.None })
    highlight(0, "goComplexes",             { fg = c.Pink, bg = c.None })
    highlight(0, "goBuiltins",              { fg = c.Yellow, bg = c.None })
    highlight(0, "goBoolean",               { fg = c.Blue, bg = c.None })
    highlight(0, "goPredefinedIdentifiers", { fg = c.Blue, bg = c.None })
    highlight(0, "goTodo",                  { fg = c.Gray, bg = c.None })
    highlight(0, "goDeclaration",           { fg = c.Blue, bg = c.None })
    highlight(0, "goDeclType",              { fg = c.Blue, bg = c.None })
    highlight(0, "goTypeDecl",              { fg = c.Blue, bg = c.None })
    highlight(0, "goTypeName",              { fg = c.BlueGreen, bg = c.None })
    highlight(0, "goVarAssign",             { fg = c.LightBlue, bg = c.None })
    highlight(0, "goVarDefs",               { fg = c.LightBlue, bg = c.None })
    highlight(0, "goReceiver",              { fg = c.Front, bg = c.None })
    highlight(0, "goReceiverType",          { fg = c.Front, bg = c.None })
    highlight(0, "goFunctionCall",          { fg = c.Yellow, bg = c.None })
    highlight(0, "goMethodCall",            { fg = c.Yellow, bg = c.None })
    highlight(0, "goSingleDecl",            { fg = c.LightBlue, bg = c.None })

    -- Python
    highlight(0, "pythonStatement",   { fg = c.Blue, bg = c.None })
    highlight(0, "pythonOperator",    { fg = c.Blue, bg = c.None })
    highlight(0, "pythonException",   { fg = c.Blue, bg = c.None })
    highlight(0, "pythonExClass",     { fg = c.BlueGreen, bg = c.None })
    highlight(0, "pythonBuiltinObj",  { fg = c.Front, bg = c.None })
    highlight(0, "pythonBuiltinType", { fg = c.BlueGreen, bg = c.None })
    highlight(0, "pythonBoolean",     { fg = c.Blue, bg = c.None })
    highlight(0, "pythonNone",        { fg = c.Blue, bg = c.None })
    highlight(0, "pythonTodo",        { fg = c.Blue, bg = c.None })
    highlight(0, "pythonClassVar",    { fg = c.Blue, bg = c.None })
    highlight(0, "pythonClassDef",    { fg = c.BlueGreen, bg = c.None })

    -- TeX
    highlight(0, "texStatement",        { fg = c.Blue, bg = c.None })
    highlight(0, "texBeginEnd",         { fg = c.Yellow, bg = c.None })
    highlight(0, "texBeginEndName",     { fg = c.LightBlue, bg = c.None })
    highlight(0, "texOption",           { fg = c.LightBlue, bg = c.None })
    highlight(0, "texBeginEndModifier", { fg = c.LightBlue, bg = c.None })
    highlight(0, "texDocType",          { fg = c.Pink, bg = c.None })
    highlight(0, "texDocTypeArgs",      { fg = c.LightBlue, bg = c.None })

    -- Git
    highlight(0, "gitcommitHeader",        { fg = c.Gray, bg = c.None })
    highlight(0, "gitcommitOnBranch",      { fg = c.Gray, bg = c.None })
    highlight(0, "gitcommitBranch",        { fg = c.Pink, bg = c.None })
    highlight(0, "gitcommitComment",       { fg = c.Gray, bg = c.None })
    highlight(0, "gitcommitSelectedType",  { fg = c.Green, bg = c.None })
    highlight(0, "gitcommitSelectedFile",  { fg = c.Green, bg = c.None })
    highlight(0, "gitcommitDiscardedType", { fg = c.Red, bg = c.None })
    highlight(0, "gitcommitDiscardedFile", { fg = c.Red, bg = c.None })
    highlight(0, "gitcommitOverflow",      { fg = c.Red, bg = c.None })
    highlight(0, "gitcommitSummary",       { fg = c.Pink, bg = c.None })
    highlight(0, "gitcommitBlank",         { fg = c.Pink, bg = c.None })

    -- Lua
    highlight(0, "luaFuncCall",    { fg = c.Orange, bg = c.None })
    highlight(0, "luaFuncArgName", { fg = c.Front, bg = c.None })
    highlight(0, "luaFuncKeyword", { fg = c.Blue, bg = c.None })
    highlight(0, "luaLocal",       { fg = c.Blue, bg = c.None })
    highlight(0, "luaBuiltIn",     { fg = c.Blue, bg = c.None })

    -- SH
    highlight(0, "shDeref",    { fg = c.Front, bg = c.None })
    highlight(0, "shVariable", { fg = c.Front, bg = c.None })

    -- SQL
    highlight(0, "sqlKeyword",  { fg = c.Blue, bg = c.None })
    highlight(0, "sqlFunction", { fg = c.Yellow, bg = c.None })
    highlight(0, "sqlOperator", { fg = c.Blue, bg = c.None })

    -- YAML
    highlight(0, "yamlKey",      { fg = c.Blue, bg = c.None })
    highlight(0, "yamlConstant", { fg = c.Blue, bg = c.None })

    -- Gitgutter
    highlight(0, "GitGutterAdd",    { fg = c.Green, bg = c.None })
    highlight(0, "GitGutterChange", { fg = c.Orange, bg = c.None })
    highlight(0, "GitGutterDelete", { fg = c.Red, bg = c.None })

    -- Git Signs
    highlight(0, "GitSignsAdd",      { fg = c.Green, bg = c.None })
    highlight(0, "GitSignsAdd",      { fg = c.DiffGreenLight, bg = c.None })
    highlight(0, "GitSignsChange",   { fg = c.Orange, bg = c.None })
    highlight(0, "GitSignsDelete",   { fg = c.Red, bg = c.None })
    highlight(0, "GitSignsAddLn",    { fg = c.Back, bg = c.Green })
    highlight(0, "GitSignsChangeLn", { fg = c.Back, bg = c.Yellow })
    highlight(0, "GitSignsDeleteLn", { fg = c.Back, bg = c.Red })

    -- NvimTree
    highlight(0, "NvimTreeRootFolder",      { fg = c.Front, bg = c.None, bold = true })
    highlight(0, "NvimTreeGitDirty",        { fg = c.Yellow, bg = c.None })
    highlight(0, "NvimTreeGitNew",          { fg = c.Green, bg = c.None })
    highlight(0, "NvimTreeImageFile",       { fg = c.Violet, bg = c.None })
    highlight(0, "NvimTreeEmptyFolderName", { fg = c.Gray, bg = c.None })
    highlight(0, "NvimTreeFolderName",      { fg = c.Front, bg = c.None })
    highlight(0, "NvimTreeSpecialFile",     { fg = c.Pink, bg = c.None, underline = true })
    highlight(0, "NvimTreeNormal",          { fg = c.Front, bg = c.LeftDark })
    highlight(0, "NvimTreeCursorLine",      { fg = c.None, bg = c.LeftMid })
    highlight(0, "NvimTreeVertSplit",       { fg = c.Back, bg = c.Back })
    highlight(0, "NvimTreeEndOfBuffer",     { fg = c.LeftDark })
    highlight(0,"NvimTreeOpenedFolderName", { fg = c.None, bg = c.LeftDark })
    highlight(0, "NvimTreeGitRenamed",      { fg = c.GitRenamed, bg = c.None })
    highlight(0, "NvimTreeGitIgnored",      { fg = c.GitIgnored, bg = c.None })
    highlight(0, "NvimTreeGitDeleted",      { fg = c.GitDeleted, bg = c.None })
    highlight(0, "NvimTreeGitStaged",       { fg = c.GitStageModified, bg = c.None })
    highlight(0, "NvimTreeGitMerge",        { fg = c.GitUntracked, bg = c.None })
    highlight(0, "NvimTreeBookmark",        { fg = c.Green, bg = c.None })
    highlight(0, "NvimTreeExecFile",        { fg = c.Red, bg = c.None })
    highlight(0, "NvimTreeOpenedFile",      { fg = c.Front, bg = c.None })
    highlight(0, "NvimTreeModifiedFile",    { fg = c.Orange, bg = c.None })
    highlight(0, "NvimTreeGitDirty",        { fg = c.GitModified, bg = c.None })
    highlight(0, "NvimTreeGitNew",          { fg = c.GitAdded, bg = c.None })

    -- Bufferline
    highlight(0, "BufferLineIndicatorSelected", { fg = c.LeftDark, bg = c.None })
    highlight(0, "BufferLineFill",              { fg = c.None, bg = c.LeftDark })

    -- BarBar
    highlight(0, "BufferCurrent",        { fg = c.Front, bg = c.TabCurrent })
    highlight(0, "BufferCurrentIndex",   { fg = c.Front, bg = c.TabCurrent })
    highlight(0, "BufferCurrentMod",     { fg = c.Yellow, bg = c.TabCurrent })
    highlight(0, "BufferCurrentSign",    { fg = c.Front, bg = c.TabCurrent })
    highlight(0, "BufferCurrentTarget",  { fg = c.Red, bg = c.TabCurrent })
    highlight(0, "BufferVisible",        { fg = c.Gray, bg = c.TabCurrent })
    highlight(0, "BufferVisibleIndex",   { fg = c.Gray, bg = c.TabCurrent })
    highlight(0, "BufferVisibleMod",     { fg = c.Yellow, bg = c.TabCurrent })
    highlight(0, "BufferVisibleSign",    { fg = c.Gray, bg = c.TabCurrent })
    highlight(0, "BufferVisibleTarget",  { fg = c.Red, bg = c.TabCurrent })
    highlight(0, "BufferInactive",       { fg = c.Gray, bg = c.TabOther })
    highlight(0, "BufferInactiveIndex",  { fg = c.Gray, bg = c.TabOther })
    highlight(0, "BufferInactiveMod",    { fg = c.Yellow, bg = c.TabOther })
    highlight(0, "BufferInactiveSign",   { fg = c.Gray, bg = c.TabOther })
    highlight(0, "BufferInactiveTarget", { fg = c.Red, bg = c.TabOther })
    highlight(0, "BufferTabpages",       { fg = c.Front, bg = c.TabOther })
    highlight(0, "BufferTabpagesFill",   { fg = c.Front, bg = c.TabOther })

    -- IndentBlankLine
    highlight(0, "IndentBlanklineContextChar",        { fg = c.ContextCurrent, bg = c.None, nocombine = true })
    highlight(0, "IndentBlanklineContextStart",       { sp = c.ContextCurrent, bg = c.None, nocombine = true, underline = true })
    highlight(0, "IndentBlanklineChar",               { fg = c.Context, bg = c.None, nocombine = true })
    highlight(0, "IndentBlanklineSpaceChar",          { fg = c.Context, bg = c.None, nocombine = true })
    highlight(0, "IndentBlanklineSpaceCharBlankline", { fg = c.Context, bg = c.None, nocombine = true })

    -- LSP
    highlight(0, "DiagnosticError", { fg = c.Red, bg = c.None })
    highlight(0, "DiagnosticWarn",  { fg = c.Yellow, bg = c.None })
    highlight(0, "DiagnosticInfo",  { fg = c.Blue, bg = c.None })
    highlight(0, "DiagnosticHint",  { fg = c.Blue, bg = c.None })
    highlight(0, "DiagnosticUnderlineError", { fg = c.None, bg = c.None, undercurl = true, sp = c.Red })
    highlight(0, "DiagnosticUnderlineWarn",  { fg = c.None, bg = c.None, undercurl = true, sp = c.Yellow })
    highlight(0, "DiagnosticUnderlineInfo",  { fg = c.None, bg = c.None, undercurl = true, sp = c.Blue })
    highlight(0, "DiagnosticUnderlineHint",  { fg = c.None, bg = c.None, undercurl = true, sp = c.Blue })
    highlight(0, "LspReferenceText",  { fg = c.None, bg = c.PopupHighlightGray or c.PopupHighlightLightBlue })
    highlight(0, "LspReferenceRead",  { fg = c.None, bg = c.PopupHighlightGray or c.PopupHighlightLightBlue })
    highlight(0, "LspReferenceWrite", { fg = c.None, bg = c.PopupHighlightGray or c.PopupHighlightLightBlue })

    -- COC.nvim
    highlight(0, "CocHighlightText",  { fg = c.None, bg = c.PopupHighlightGray or c.PopupHighlightLightBlue })
    highlight(0, "CocHighlightRead",  { fg = c.None, bg = c.PopupHighlightGray or c.PopupHighlightLightBlue })
    highlight(0, "CocHighlightWrite", { fg = c.None, bg = c.PopupHighlightGray or c.PopupHighlightLightBlue })

    -- Nvim compe
    highlight(0, "CmpItemKindVariable",    { fg = c.LightBlue, bg = c.None })
    highlight(0, "CmpItemKindInterface",   { fg = c.BlueGreen, bg = c.None })
    highlight(0, "CmpItemKindText",        { fg = c.LightBlue, bg = c.None })
    highlight(0, "CmpItemKindFunction",    { fg = c.Yellow, bg = c.None })
    highlight(0, "CmpItemKindMethod",      { fg = c.Yellow, bg = c.None })
    highlight(0, "CmpItemKindKeyword",     { fg = c.Front, bg = c.None })
    highlight(0, "CmpItemKindProperty",    { fg = c.Front, bg = c.None })
    highlight(0, "CmpItemKindUnit",        { fg = c.Front, bg = c.None })
    highlight(0, "CmpItemKindConstructor", { fg = c.BlueGreen, bg = c.None })
    highlight(0, "CmpItemMenu",            { fg = c.PopupFront, bg = c.None })
    highlight(0, "CmpItemAbbr",            { fg = c.Front, bg = c.None })
    highlight(0, "CmpItemAbbrDeprecated",  { fg = c.CursorDark, bg = c.PopupBack, strikethrough = true })
    highlight(0, "CmpItemAbbrMatch",       { fg = c.LightBlue or c.DarkBlue, bg = c.None, bold = true })
    highlight(0, "CmpItemAbbrMatchFuzzy",  { fg = c.LightBlue or c.DarkBlue, bg = c.None, bold = true })

    -- Dashboard
    highlight(0, "DashboardHeader",   { fg = c.Blue, bg = c.None })
    highlight(0, "DashboardDesc",     { fg = c.Yellow, bg = c.None })
    highlight(0, "DashboardIcon",     { fg = c.Yellow, bg = c.None })
    highlight(0, "DashboardShortCut", { fg = c.Pink, bg = c.None })
    highlight(0, "DashboardKey",      { fg = c.White, bg = c.None })
    highlight(0, "DashboardFooter",   { fg = c.Blue, bg = c.None, italic = true })

    highlight(0, "NvimTreeFolderIcon",   { fg = c.Front, bg = c.None })
    highlight(0, "NvimTreeIndentMarker", { fg = c.LineNumber, bg = c.None })

    highlight(0, "LspFloatWinNormal",             { fg = c.Front, bg = c.None })
    highlight(0, "LspFloatWinBorder",             { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspInfoBorder",                 { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaHoverBorder",            { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaSignatureHelpBorder",    { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaCodeActionBorder",       { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaDefPreviewBorder",       { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspLinesDiagBorder",            { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaRenameBorder",           { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaBorderTitle",            { fg = c.CursorDark, bg = c.None })
    highlight(0, "LSPSagaDiagnosticTruncateLine", { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaDiagnosticBorder",       { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaDiagnosticBorder",       { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaShTruncateLine",         { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaShTruncateLine",         { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaDocTruncateLine",        { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaRenameBorder",           { fg = c.LineNumber, bg = c.None })
    highlight(0, "LspSagaLspFinderBorder",        { fg = c.LineNumber, bg = c.None })

    highlight(0, "TelescopePromptBorder",   { fg = c.LineNumber, bg = c.None })
    highlight(0, "TelescopeResultsBorder",  { fg = c.LineNumber, bg = c.None })
    highlight(0, "TelescopePreviewBorder",  { fg = c.LineNumber, bg = c.None })
    highlight(0, "TelescopeNormal",         { fg = c.Front, bg = c.None })
    highlight(0, "TelescopeSelection",      { fg = c.Front, bg = c.Selection })
    highlight(0, "TelescopeMultiSelection", { fg = c.Front, bg = c.PopupHighlightBlue })
    highlight(0, "TelescopeMatching",       { fg = c.LightBlue, bg = c.None, bold = true })
    highlight(0, "TelescopePromptPrefix",   { fg = c.Front, bg = c.None })

    -- symbols-outline
    -- white fg and lualine blue bg
    highlight(0, "FocusedSymbol",           { fg = "#ffffff", bg = c.Blue })
    highlight(0, "SymbolsOutlineConnector", { fg = c.LineNumber, bg = c.None })
end

return theme
